# Dot at end of line makes it clearer that the line is not done
Layout/DotPosition:
  EnforcedStyle: trailing

# Test describe blocks can be any length
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'features/**/*'

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# Prefer parentheses in method definitions
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# I like to have symbols always look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets
